pipeline:
  name: pismo-jpbarto-promotion-pipeline
  identifier: pismojpbartopromotionpipeline
  projectIdentifier: pismojpbartopromotion
  orgIdentifier: pismo
  tags: {}
  stages:
    - stage:
        name: Preparation
        identifier: Preparation
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo examine the trigger event
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo doing prep stuff
                          git clone https://github.com/jpbarto/harness-env
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: release_repository
      type: String
      description: ""
      required: true
      value: <+eventPayload.repository.html_url>
    - name: release_tag
      type: String
      description: ""
      required: false
      value: <+eventPayload.release.tag_name>
